### ISSUE TITLE
[Request] Auto Update

### ISSUE THREAD

**Issue by 4LaERz0GWNnuZqmnH** [xManager-App/xManager#145]
Problem:
I use this app on multiple phones throughout work that I give to others. These people will never update Spotify through the manager due to lack of technical know-how. If I am not there to do it for them, Spotify will fall out of date. 

Solution:
Please include an auto update option for Spotify. The app already detects the version needed, so the ability to have to automatically download and install would be extremely useful.

If possible/not too difficult, the ability to choose when it updates, so that I can have it done at midnight instead of while they're listening to music. 

Additional Context:
My issue is the people I have it set up for (nice old Mexican grandma's who don't speak any English for me to explain the process) are not technically savvy. A toast notification that there's an update available is most likely too much for them, which is why I didn't list that as an alternative. A completely automated approach would be best in this scenario. 

Thanks for reading

**Comment by spider1163** [comment]
I don't think it's possible to update (i.e. install an apk) without user intervention, unless you are root #173, or using the latest Android 12 features #116

**Comment by soredake** [comment]
@spider1163 it's possible without root and without android 12 with https://shizuku.rikka.app/

**Comment by generic-glitch** [comment]
Not many changes here in sometime, but ler's say I'm not a grandma and do have shizuku installed already (albeit for other apps), how could one go about making this work with android auto?

**Comment by energ0n** [comment]
Since latest version is not always the best for all devices (or may have issues in general), users who are not tech-savvy should probably not be auto-updating their modded apps. 

Such a feature is currently not planned, so we'll be closing this issue for now.
