### ISSUE TITLE
Using latest version, downloads do not seem to start

### ISSUE THREAD

**Issue by morpheasgr** [xManager-App/xManager#147]
Greetings, using newest version, both after watching ads or attempting again with deactivated reward ads, I am unable to get any download to start. Download at 0% with no filesize getting calculated. I noticed the copy URL links to bit.ly or some shortener - perhaps with inline ads. How does the in-app downloader work? Does it send an HTTP get request? In case you through the shortened links to it are you sure they are properly resolved? Maybe the hosting does not allow hotlinking? Via browser I am able to initiate the download normally.

In case your app uses the stock Android "downloader" maybe some unbloating/permission tweaks I did are the cause.

I am on android 11 and enabled all files access, even though I use other apps such as web browsers who are able to store files both within their directories and in the downloads folder so I am not sure why this is utilized.

In my browser I use private DNS, I will try whether my ISP's DNS is blocking it.

PS: I am on 5G, mobile data.

**Comment by fredfred41** [comment]
same situation for me, did you find any workaround? thanks

**Comment by energ0n** [comment]
Outdated xManager build -- closing issue. 
If issue persists in current version, please open a new `Issue` and use issue template.
