### ISSUE TITLE
Auto install/update app for rooted devices at background

### ISSUE THREAD

**Issue by thanasistrisp** [xManager-App/xManager#173]
**Is your feature request related to a problem? Please describe.**
Everytime it exists an update, I should accept prompt to update the app.
**Describe the solution you'd like**
Check periodically at background for updates (and be able to choose sync interval) and auto install them with root (super) privileges.

**Comment by energ0n** [comment]
Thank you for the idea. 
This feature is currently not planned. Closing for now.
