### ISSUE TITLE
xManager app not loading, cannot install or view app versions

### ISSUE THREAD

**Issue by ratchetchan** [xManager-App/xManager#241]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy S20+
- Android Version:  12
- ROM Version:  stock
- xManager Version:  2.8
```

### 📝 Description

1. Open app
2. App never stops loading animation
3.
...

### 📸 Screenshots

![Uploading Screenshot_20221225-210213_xManager.jpg…]()

**Comment by energ0n** [comment]
outdated xManager build -- closing.
if issue persists on current version please open a new `issue` using the `bug report` template.
