### ISSUE TITLE
copy url not working

### ISSUE THREAD

**Issue by Tetrax-10** [xManager-App/xManager#243]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Moto G51 5G
- Android Version:  12
- ROM Version:  stock
- xManager Version:  xManager v4.3
```

### 📝 Description

I click copy url it says sucessfully copied, but when i see the clip board there is noting.

**Comment by moeinmhzg** [comment]
Same here with 
- Samsung Galaxy A51
- Android 13.0
- xManager 4.3

**Comment by energ0n** [comment]
Issue noted. Will hopefully be solved in a future update. In the meantime, options are: 
-uninstall v4.3 and downgrade to xManager v4.2
-download mod in-app
-download from tg support group

**Comment by xC3FFF0E** [comment]
Copy Url should be working by now. Let us know if the issue persists.

**Comment by Tetrax-10** [comment]
Thx for fixing the issue. It's working fine now.
