### ISSUE TITLE
App renames itself, then never opens again

### ISSUE THREAD

**Issue by VioletStorm** [xManager-App/xManager#244]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  ROG Phone 6
- Android Version:  A12
- ROM Version:  stock
- xManager Version:  4.3
```

### 📝 Description

1. Install modded Spotify
2. Wait (it works for a while)
3. App renames itself to "Recommended" and crashes immediately when opened

**Comment by energ0n** [comment]
Based on the description, this is not an issue with the xManager app itself but instead with the mod or phone itself. Closing issue as this is outside the scope of this repo.
