### ISSUE TITLE
Remember Filters

### ISSUE THREAD

**Issue by VioletStorm** [xManager-App/xManager#245]
### Description of the new feature / enhancement

Have the selected playlist filters persist between app restarts, this would be a QoL addition which would make getting to your preferred playlists a bit more streamlined

### 📸 Screenshots

![Screenshot_20221229-130455_Spotify](https://user-images.githubusercontent.com/54405427/209992254-2098105d-c610-455d-a650-a3f290494875.png)

**Comment by energ0n** [comment]
This is not an xManager issue and deals with Spotify. Please only use this repo for its intended purposes.
