### ISSUE TITLE
[Feature Request] Transparent navigation bar in lyrics view

### ISSUE THREAD

**Issue by Seanathan10** [xManager-App/xManager#246]
### Description of the new feature / enhancement

When viewing the lyrics of a song, it doesn't look very clean because of the presence of the black navigation bar. Since this is a modified version, is it possible for the nav bar to be hidden? For example, when viewing canvas mode of a song, the navigation bar completely disappears and the app switches into immersive mode. Meanwhile in the lyrics view, the app only hides the status bar. I have attached some screenshots to show what I mean. Thank you for this excellent mod.

### 📸 Screenshots

![Screenshot_20221229-202646](https://user-images.githubusercontent.com/38306929/210034555-c773f82f-8343-42e2-96d1-4ea2444b0aa3.png)

Above is the first screenshot and as you can see the navigation bar is visible and creates a black overlay on top of the lyrics. This unfortunately results in a very unclean look.

![Screenshot_20221229-202812](https://user-images.githubusercontent.com/38306929/210034556-3871b2cc-28d9-48c3-a231-a6505f7f97e6.png)

This is a second screenshot I took in Spotify's canvas mode. When an artist's GIF is displayed here, the app hides both the status and navigation bars and it results in a very clean, full screen, look.

My Samsung S20 allows for the hiding of the navigation bar and would you lets me have a clean full screen look. However, this feature is not available on the Pixel lineup. I'm not sure if it's available on other devices. 

I really hope that this can be changed. I posted the same issue on Spotify's feature request forms but they took it down pretty quickly stating that it was out of their control. 

Thank you!

Photos:
Samsung S20:
![PXL_20221230_043358354~2](https://user-images.githubusercontent.com/38306929/210034995-f63b78db-0dfd-40e2-9f14-10ccab075c57.jpg)
Pixel 7:
![20221229_203813](https://user-images.githubusercontent.com/38306929/210034997-036350f6-defb-4712-b9b1-d15f190f2d7e.jpg)

**Comment by energ0n** [comment]
This is not an xManager issue and deals with Spotify. Please only use this repo for its intended purposes.
