### ISSUE TITLE
Infinite Skips not working on a Google Pixel 6

### ISSUE THREAD

**Issue by L8X** [xManager-App/xManager#249]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
Pixel 6 
Android 13
stock
```

### 📝 Description

Skip a few times, it'll stop you skipping further.

**Comment by energ0n** [comment]
This is not an xManager issue and deals with Spotify. Please only use this repo for its intended purposes.
