### ISSUE TITLE
Showing Advertisement

### ISSUE THREAD

**Issue by mjain234** [xManager-App/xManager#255]
I have been using Spotify (downloaded from xmanager) since a month but never faced this advertisement. Is this a recent issue or am I the only one seeing this ![ad](https://user-images.githubusercontent.com/70900505/214005101-998e747e-577e-46a9-9bac-00d3db32dc69.png)

Android version ~ Android 13

Device ~ Realme 2 Pro

ROm ~ Arrow OS

**Comment by energ0n** [comment]
This repo is to be used for xManager and xManager issues. Feel free to submit a detailed bug report in one of the support communities (Discord/Telegram/Reddit). Please read the FAQ in-app (xManager) first as well.

Closing.
