### ISSUE TITLE
Add Friends Activity Menu

### ISSUE THREAD

**Issue by sakgoyal** [xManager-App/xManager#256]
### Description of the new feature / enhancement

Is it possible to add a way to see what your friends/followers are listening to in the mobile app? I like the desktop app which does this but the mobile one doesnt. is there a way to implement it yourself here? 

I saw this repo and I thought it might be possible to do that using a similar method to that
https://github.com/valeriangalliat/spotify-buddylist

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
