### ISSUE TITLE
Completely/Truly Random Shuffle

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [xManager-App/xManager#257]
### Description of the new feature / enhancement

Like the title says, make shuffle actually randomize what song get played next. 

For example, if you  have a playlist with 50 songs every song in the playlist has a 1/50 chance to be played next, or if the playlist has 100 songs each song will have a 1/100 chance, or if your playlist has a 183 songs each song will have a 1/183 chance to be played next.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
