### ISSUE TITLE
Use an external downloader to download songs and playlists

### ISSUE THREAD

**Issue by Radical4ever** [xManager-App/xManager#258]
### Description of the new feature / enhancement

- 1 use another downloader knowing well that the inapp one cannot be enabled bc its a server thing
- 2 probably adding a new entry on the menu to dow load the song or in other case on the share screen shows the option to download
- 3 music could be choose were to be saved alongside other stuff (like lyrics and the cover if it is possible)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
