### ISSUE TITLE
android auto support

### ISSUE THREAD

**Issue by finland** [xManager-App/xManager#261]
### Description of the new feature / enhancement

I don't know how feasible this is to implement but would be nice

**Comment by energ0n** [comment]
The issues section in this repo is exclusively for the xManager app itself. Anything else is outside the scope of this repo.

**Comment by jacobceles** [comment]
Duplicate of #114. 
@finland: You need to enable unknown sources in Android Auto on your phone. Open AA and click version 10 times to access developer options.
