### ISSUE TITLE
The updates can be faster

### ISSUE THREAD

**Issue by BadBoy-Github** [xManager-App/xManager#263]
### Description of the new feature / enhancement

- Current spotify version : 8.8.6.472
- Xmanager spotify version : 8.8.4.518
Updating the apps in the Xmanager frequently could be helpful.

**Comment by energ0n** [comment]
This repo and issue section is for xManager-specific issues only. Anything related to Spotify or "non-xManager things" is outside the scope of this repo.

Due to time constraints, versions provided by xManager will never be as frequent as official releases.
