### ISSUE TITLE
TV version

### ISSUE THREAD

**Issue by nicesapien-too** [xManager-App/xManager#265]
A Android TV modded Spotify version would be really great as i mostly use my tv to stream music. It woulf be useful for others too. Please add it.

**Comment by energ0n** [comment]
There are currently no plans for xManager to support Android TV or any other devices outside of the current scope (mobile devices and tablets).

**Comment by energ0n** [comment]
There are currently no plans for xManager to support Android TV or any other devices outside of the current scope (mobile devices and tablets).

**Comment by DarkCrypt** [comment]
I found an old tv mod still working on Android TV 10 you can try.
