### ISSUE TITLE
xManager crashing to desktop

### ISSUE THREAD

**Issue by Pro-cyber-byte** [xManager-App/xManager#267]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Infinix S5  
- Android Version: Android 9 (Pie)  
- ROM Version: Stock (4.9.117+) with Magisk system-as-root
- xManager Version:  xManager 4.4
```

### 📝 Description

1. Upon opening app , apps displays "No API response".
2. On pulling down to refresh API's , app Crashes to desktop and then shows error as described in the screenshot. 
3. Fresh install and clearing app folder manually rendered useless. Noticed the error today itself for the first time.
4. Most likely related to the API not responding , checking API status on github homepage also mentions API status invalid as of the time of typing this. 

### 📸 Screenshots

![Screenshot_20230223-173725](https://user-images.githubusercontent.com/67885593/220919660-267a8e51-1835-4844-ab0f-64179be3925d.png)

**Comment by Foxydroid** [comment]
This is what I have.
- Device Model: Poco X3 Pro
- Android Version: Android 13 (Tiramisu)
- ROM Version: EvolutionX (4.14.302) with Magisk system-as-root
- xManager Version:  xManager 4.4

**Comment by joecross98** [comment]
The webpage shows API status Up, but I'm still getting the error.  Reinstalled, no luck.

**Comment by Pro-cyber-byte** [comment]
> 

Yeah , the problem persists for me as well even after the API status shows up ..

**Comment by energ0n** [comment]
Issue related to https://github.com/xManager-App/xManager/issues/266 

Closing this...
