### ISSUE TITLE
Latest manager doesn't show versions 

### ISSUE THREAD

**Issue by GodsMasterpiece509** [xManager-App/xManager#268]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: poco X3 nfc 
- Android Version: Android 12
- ROM Version:MIUI 13
- xManager Version: 4.5
```

### 📝 Description

1.
2.
3.
...
..

### 📸 Screenshots

![IMG_20230223_133312](https://user-images.githubusercontent.com/118909295/221011547-5cb2f713-ef98-4789-ad0f-655b042c3561.jpg)

**Comment by CoffeeNData** [comment]
Not working indeed, I have the same issue. Only Lite version works.

**Comment by EDM115** [comment]
Same issue here :  

![Screenshot_2023-02-23-23-42-56-798_com xc3fff0e xmanager](https://user-images.githubusercontent.com/82015596/221047462-3aa7f2b9-6a23-47c0-9e6d-1cf29f612f02.jpg)

![Screenshot_2023-02-23-23-42-58-460_com xc3fff0e xmanager](https://user-images.githubusercontent.com/82015596/221047429-6d0cc14d-f2cd-4da0-b2c6-b641f1e55176.jpg)

![Screenshot_2023-02-23-23-42-53-791_com xc3fff0e xmanager](https://user-images.githubusercontent.com/82015596/221047489-85dc2473-fb4b-48ca-a9e0-0560fc4b4445.jpg)

**Comment by GodsMasterpiece509** [comment]
> Same issue here :  
> 
> ![Screenshot_2023-02-23-23-42-56-798_com xc3fff0e xmanager](https://user-images.githubusercontent.com/82015596/221047462-3aa7f2b9-6a23-47c0-9e6d-1cf29f612f02.jpg)
> 
> ![Screenshot_2023-02-23-23-42-58-460_com xc3fff0e xmanager](https://user-images.githubusercontent.com/82015596/221047429-6d0cc14d-f2cd-4da0-b2c6-b641f1e55176.jpg)
> 
> ![Screenshot_2023-02-23-23-42-53-791_com xc3fff0e xmanager](https://user-images.githubusercontent.com/82015596/221047489-85dc2473-fb4b-48ca-a9e0-0560fc4b4445.jpg)
> 

We might have to wait for a Fix on this matter That is why I posted it right away Blessings

**Comment by madhurvarshney** [comment]
Yes

**Comment by xC3FFF0E** [comment]
Download the hot-fixed here: https://github.com/xManager-App/xManager/releases/download/4.5/xManager.apk

Once installed, clear data and disable your VPN/Proxy when using the app. If the issue persists, let me know. Thanks!

**Comment by EDM115** [comment]
> Download the hot-fixed here: https://github.com/xManager-App/xManager/releases/download/4.5/xManager.apk
> 
> Once installed, clear data and disable your VPN/Proxy when using the app. If the issue persists, let me know. Thanks!

Works like a charm, thanku 🥺

**Comment by EDM115** [comment]
except... Older versions still don't show

**Comment by xC3FFF0E** [comment]
> except... Older versions still don't showsmiling_face_with_tear
> 
> ![Screenshot_2023-02-24-15-28-01-446_com.xc3fff0e.xmanager.jpg](https://user-images.githubusercontent.com/82015596/221203209-48576297-d767-4265-80da-9efe18c84387.jpg)

There's a reason for that. Since we're introducing experimenal versions, all older versions have a/b features enabled are gone (for now). These older versions will be soon release to experimental versions while stock patches will act just a regular premium.

**Comment by EDM115** [comment]
> There's a reason for that. Since we're introducing experimenal versions, all older versions have a/b features enabled are gone (for now). These older versions will be soon release to experimental versions while stock patches will act just a regular premium.  
  
okay, i understand better now 🥺

**Comment by GodsMasterpiece509** [comment]
> Download the hot-fixed here: https://github.com/xManager-App/xManager/releases/download/4.5/xManager.apk
> 
> Once installed, clear data and disable your VPN/Proxy when using the app. If the issue persists, let me know. Thanks!

Thanks Its working Now Thanks for the Response i Appreciate you

**Comment by GodsMasterpiece509** [comment]
> > Download the hot-fixed here: https://github.com/xManager-App/xManager/releases/download/4.5/xManager.apk
> > 
> > Once installed, clear data and disable your VPN/Proxy when using the app. If the issue persists, let me know. Thanks!
> 
> Thanks Its working Now Thanks for the Response i Appreciate you 

Oh yeah like in comments here other versions aren't visible

**Comment by twistedmacaroni** [comment]
> Download the hot-fixed here: https://github.com/xManager-App/xManager/releases/download/4.5/xManager.apk
> 
> Once installed, clear data and disable your VPN/Proxy when using the app. If the issue persists, let me know. Thanks!

The issue is still there is experimental features toggle is set to on.

**Comment by dam1nn** [comment]
> 
> > Once installed, clear data and disable your VPN/Proxy when using the app. If the issue persists, let me know. Thanks!
> 
> In my country, because of Internet censorship, xmanager only worked with a VPN! now I can't use it.

same here

**Comment by xC3FFF0E** [comment]
Hi. xManager v4.6 update is now available. This update should resolve most of our user's concerns and issues. Kindly check the changelogs for further details about the update. Thanks!

**Important Note:** If you're still unable to see any list items, versions or latest; use the 'Refetch and Reboot' functionality at the settings.

**Comment by Shituation** [comment]
I can only see the lite versions. Is this intended?
