### ISSUE TITLE
It just keeps me telling download when , I press the download button takes me to an ad I try viewing it until I get reward granted but I can't still download


### ISSUE THREAD

**Issue by b-aragu** [xManager-App/xManager#270]

**Comment by Applewubs** [comment]
This also happens to me on some devices, others work normally

**Comment by xC3FFF0E** [comment]
Use the mirror link else visit our support group to get our releases.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
