### ISSUE TITLE
App not installed as package appears to be invalid

### ISSUE THREAD

**Issue by tzaqam** [xManager-App/xManager#271]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [x] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Galaxy Tab S7
- Android Version:  13
- ROM Version:  
- xManager Version:  4.5
```

### 📝 Description

1. Download & install any version
2. Doesnt install: App not installed as package appears to be invalid
3.
...

Lite version seems to be fine

**Comment by amd64fo** [comment]
same here
Device Model: Huawei Nova 8
Android Version:12
xManager Version:  4.5

**Comment by xC3FFF0E** [comment]
Hi. xManager v4.6 update is now available. This update should resolve most of our user's concerns and issues. Kindly check the changelogs for further details about the update. Thanks!

**Important Note:** If you're still unable to see any list items, versions or latest; use the 'Refetch and Reboot' functionality at the settings.

**Comment by msr8** [comment]
Doesnt work for me in xManager 4.6

![image](https://user-images.githubusercontent.com/79649185/222387328-cbe63102-a480-4810-880a-62d2d56287a4.png)

![image](https://user-images.githubusercontent.com/79649185/222388189-c9b12395-fa94-49e1-ae38-4596cbabfa5c.png)


Also, it is unable to download the file too. So in the download screen, I clicked "MIRROR LINK", downloaded the spotify apk from gofile, and the file I downloaded gave me this error when trying to install it:

![image](https://user-images.githubusercontent.com/79649185/222388224-4bafe90a-4d63-4f06-8666-8664db250ebb.png)

(I was able to install it succesfully when I downloaded it through zippyshare on xmanager 4.5. though

**Comment by xC3FFF0E** [comment]
![IMG_20230302_175133](https://user-images.githubusercontent.com/78732474/222393844-70462417-8f6f-47d3-9b65-0ec49742dfe7.jpg)

**Comment by xC3FFF0E** [comment]
Not a manager issue but instead an incomplete download.
