### ISSUE TITLE
Tidal support?

### ISSUE THREAD

**Issue by jim16127** [xManager-App/xManager#274]
### Description of the new feature / enhancement

Any possibility Tidal could be implemented as well?

**Comment by xC3FFF0E** [comment]
We don't have any plans adding Tidal in the manager app but instead an exclusive release.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
