### ISSUE TITLE
Labs - Experimental Version showing 0000

### ISSUE THREAD

**Issue by vrindavan** [xManager-App/xManager#275]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Galaxy M21, A51
- Android Version:  Android 12
- ROM Version:  OneUI 4
- xManager Version:  4.5
```

### 📝 Description

1. Switch on labs - Experimental Patches
2. Refresh
3. Version is showing Latet - 0000
...

### 📸 Screenshots

![Screenshot_20230226-083642_xManager](https://user-images.githubusercontent.com/50140643/221390072-de5b2035-f509-4c19-9984-fc902a9ba841.png)

**Comment by xC3FFF0E** [comment]
Experimental Versions are not yet available. These 0.0.0.000 are just a place holder versions.
