### ISSUE TITLE
No version is displayed after updating to version 4.5

### ISSUE THREAD

**Issue by xxspobbixx** [xManager-App/xManager#276]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy S22
- Android Version:  13
- ROM Version:  
- xManager Version:  4.5
```

### 📝 Description

After updating to version 4.5, no version is displayed which is currently installed or which is currently available

### 📸 Screenshots

https://ibb.co/tqRbFhp

**Comment by BobbyESP** [comment]
https://user-images.githubusercontent.com/60316747/221434498-e7323ff4-95d4-469a-becb-9dc9065bb2ee.mp4

**Comment by xxspobbixx** [comment]
Thank you :-)

**Comment by BabyOilJohnson** [comment]
Related to #268

**Comment by solirf** [comment]
![Screenshot_2023-02-28-10-45-56-022_com xc3fff0e xmanager](https://user-images.githubusercontent.com/18699138/221781216-910b06b7-86e3-43b1-8a6a-2b3c6bb262c3.jpg)

VPN is Off
Experimental version is off
Still version not showing after update to 4.5

**Comment by chacha121** [comment]
> ![Screenshot_2023-02-28-10-45-56-022_com xc3fff0e xmanager](https://user-images.githubusercontent.com/18699138/221781216-910b06b7-86e3-43b1-8a6a-2b3c6bb262c3.jpg)
> 
> VPN is Off Experimental version is off Still version not showing after update to 4.5

same issue

**Comment by solirf** [comment]
Thank you 😊 , V4.6 works like a charm
