### ISSUE TITLE
4.5version keeps crashing as it launch 

### ISSUE THREAD

**Issue by rayhur** [xManager-App/xManager#277]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy S21Plus
- Android Version:  Android13
- ROM Version:  5.4.147
- xManager Version:  4.5
```

### 📝 Description

Just updated xManager4.3 to latest version 4.5. After installing tried to launch app, it is but just keeps crashing. I

**Comment by jason88fr** [comment]
Same here, no crash dialog either, just closes

**Comment by juleshwar** [comment]
If you have a VPN connection, turn it off and open the app. 
That was the reason for the crash in my case.

**Comment by xC3FFF0E** [comment]
Hi. xManager v4.6 update is now available. This update should resolve most of our user's concerns and issues. Kindly check the changelogs for further details about the update. Thanks!

**Comment by Eagle00Eye** [comment]
I can confirm v4.6 now works while my ExpressVPN is connected.

Love your work!
