### ISSUE TITLE
DETECTED TROJAN

### ISSUE THREAD

**Issue by HARDWARE23** [xManager-App/xManager#278]
Xmanager itself is just an installer for the cracked Spotify and is harmless. HOWEVER the Spotify that is installed was immediately detected as Trojan by my OS security software. I later ran through some tests on Virustotal and it was too detected there.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
