### ISSUE TITLE
Can't download playlist.

### ISSUE THREAD

**Issue by Honkychunkymonkey** [xManager-App/xManager#279]
When I hit the download button on a playlist, the button lights up, but nothing gets actually downloaded.

**Comment by WadieBenabdouh** [comment]
@Honkychunkymonkey you can't download songs using this modded Spotify app, the download option is only available in the original spotify app.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
