### ISSUE TITLE
Trouble with installing cloned version

### ISSUE THREAD

**Issue by fen0men102** [xManager-App/xManager#283]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Samsung Galaxy S21
- Android Version: 13
- ROM Version: stock 
- xManager Version: 4.6
```

### 📝 Description

If you are trying to install the cloned version through the xmanager while having regular one with higher version number, it says that "the patched version is lower than what is currently installed". When you try installing with file, everything works ok.

### 📸 Screenshots

![Screenshot_20230306_003234_xManager](https://user-images.githubusercontent.com/69432581/222987304-1208a1d7-4d56-471f-8e2e-59251b7e1fb0.jpg)
![Screenshot_20230306_003221_xManager](https://user-images.githubusercontent.com/69432581/222987305-5788e41d-905a-4438-894e-8e25bc23197d.jpg)

**Comment by xC3FFF0E** [comment]
This issue has been resolved in the latest version. Kindly update to v4.7 to see the changes. If the issue persists, let me know. Thanks!
