### ISSUE TITLE
Spotify stops again and again

### ISSUE THREAD

**Issue by conveyorBeltOverlord** [xManager-App/xManager#284]
No matter what i trying it just stops, any advice?

**Comment by energ0n** [comment]
GitHub issues should only be used for xManager app specific issues only.
Any and all issues, requests and discussions not related to the code in this repo falls outside the scope of the xManager repo and should be moved to our "social media" support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
