### ISSUE TITLE
Stock Patch and AMOLED patch don't update.

### ISSUE THREAD

**Issue by CallumJThompson** [xManager-App/xManager#286]
I noticed that xmanager kept crashing when opening with no error of any kind, so I reinstalled it from the website (xmanager app.com), updated the data list and now stock and AMOLED don't show any versions and the lite patch shows very few. 
Edit: I'm on latest version (4.6)  android 13 latest... 
![Screenshot_20230307-124200](https://user-images.githubusercontent.com/36814754/223425120-dda03cb3-8c49-4e27-8186-3f4bd7b37e61.png)
![Screenshot_20230307-124157](https://user-images.githubusercontent.com/36814754/223425126-db99341e-104a-4abd-ae8b-43f7adf2004c.png)
![Screenshot_20230307-123943](https://user-images.githubusercontent.com/36814754/223425128-d25dc4cb-8f92-4839-9981-329e63937da0.png)

**Comment by energ0n** [comment]
Toggling the 'Refetch and Reboot'  button under Settings should help. Or toggling "experimental version" option under the Experimental settings (lab beaker icon) on and off again. 

https://github.com/xManager-App/xManager/issues/277#issuecomment-1448915985

**Comment by CallumJThompson** [comment]
That did seem to work, before adding 'experimental versions' updating only showed the newest versions. Which isn't really an issue since that's what I'm looking for, but still odd that previous versions aren't showing like they used to. And experimental versions only show some rollback versions from a long while ago, so some older versions are clearly missing?

Either way, solution did refresh the lists with the newest versions of the app, so that's the main thing. Will close.
