### ISSUE TITLE
Manager version display error

### ISSUE THREAD

**Issue by Maremelows** [xManager-App/xManager#287]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy A23
- Android Version:  Android 13
- ROM Version:  stock
- xManager Version:4.6
```

### 📝 Description

1.
2.
3.
...
The first photo shows it without the experimental release feature turned on./The second photo shows it with the experimental release feature turned on.When the experimental version is on, my last downloaded version does not show up.

### 📸 Screenshots

![Screenshot_20230307_143514_xManager](https://user-images.githubusercontent.com/125856651/223506165-bb0cb840-4035-4c72-98fe-4cdb006223e5.jpg)
![Screenshot_20230307_143440_xManager](https://user-images.githubusercontent.com/125856651/223506178-75785928-9afb-4eee-8082-a6bb2c7cd923.jpg)

**Comment by TheJeterLP** [comment]
They're called experimental for a reason

**Comment by xC3FFF0E** [comment]
This issue has been resolved in the latest version. Kindly update to v4.7 to see the changes. If the issue persists, let me know. Thanks!
