### ISSUE TITLE
Volumio connect not working

### ISSUE THREAD

**Issue by dakkar96** [xManager-App/xManager#288]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  S7 edge
- Android Version: e/os 
- ROM Version:  stock
- xManager Version:  4.6
```

### 📝 Description

Volumio connect not working. Only available for premium users. I do not encounter this issue with other devices such as Nvdia Shield. But I didn't have this issue with the older version for example. I know it's a spotify-mod issue but I couldn't find the right place to ask for a solution.

thank you for all your work ! much appreciated

### 📸 Screenshots

![Screenshot_20230308-181458_Spotify](https://user-images.githubusercontent.com/127337370/223791762-eb1b3022-b694-4c8b-8863-cb4fccc1610d.png)

**Comment by energ0n** [comment]
GitHub issues should only be used for xManager app specific issues only.
Any and all issues, requests and discussions not related to the code in this repo falls outside the scope of the xManager repo and should be moved to our "social media" support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
