### ISSUE TITLE
Patched Spotify keeps crashing after login

### ISSUE THREAD

**Issue by dwnppoalt** [xManager-App/xManager#289]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy A10
- Android Version:  Android 11
- ROM Version:  stock
- xManager Version:  4.6
```

### 📝 Description

After logging in on both stock patched and amoled patched spotify, the app just keeps crashing. I tried force stop, but it didn't work.

**Comment by energ0n** [comment]
GitHub issues should only be used for xManager app specific issues only.
Any and all issues, requests and discussions not related to the code in this repo falls outside the scope of the xManager repo and should be moved to our "social media" support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
