### ISSUE TITLE
Can't cast to Spotify Connect device?

### ISSUE THREAD

**Issue by BrodyStone21** [xManager-App/xManager#291]
Hello, I am having issues with casting to a Spotify Connect device. I'm receiving a message stating that this is unavailable for free users. It does appear ad-free and unlimited skips is working correctly. 

Is there any way to get this working with this mod?

![Screenshot_20230310-084354](https://user-images.githubusercontent.com/36679309/224331542-df34152d-2751-4f89-a01d-e00589958ee4.png)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
