### ISSUE TITLE
Won't let me force close Spotify after install

### ISSUE THREAD

**Issue by weole** [xManager-App/xManager#293]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Motorola g play
- Android Version:  Android 11
- ROM Version:  stock
- xManager Version:  4.7
```

### 📝 Description

1.Tells me to force close the app
2. Go into Settings
3. Hits the force close button expecting it to work but it does nothing instead.
...

**Comment by KevinNitroG** [comment]
Yes Spotify kept running even I tried force it to stop.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
