### ISSUE TITLE
xmanager-spotify Android Auto

### ISSUE THREAD

**Issue by iansalgado** [xManager-App/xManager#296]
### Description of the new feature / enhancement

Hi,

i just wanted to find out if xmanager-spotify supports android auto unit.

I have one of these unit but i can't get the spotify app to show on the menu so that i can use it.

cheers

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by jacobceles** [comment]
Duplicate of #114. 
@iansalgado: You need to enable unknown sources in Android Auto on your phone. Open AA and click version 10 times to access developer options.

**Comment by iansalgado** [comment]
Tried that. In fact, my phone was already in developer mode but still didn't work

Ian Salgado
Email: ***@***.***
Mobile: 0415 515 086


-------- Original message --------
From: Jacob Celestine ***@***.***>
Date: Thu, 30 Mar 2023, 01:01
To: xManager-App/xManager ***@***.***>
Cc: iansalgado ***@***.***>, Mention ***@***.***>
Subject: Re: [xManager-App/xManager] xmanager-spotify Android Auto (Issue #296)

Duplicate of #114<https://github.com/xManager-App/xManager/issues/114>.
@iansalgado<https://github.com/iansalgado>: You need to enable unknown sources in Android Auto on your phone. Open AA and click version 10 times to access developer options.

**Comment by jacobceles** [comment]
@iansalgado Not your phone. You need to enable Android Auto developer settings. Go to settings, open android auto, click the version a few times and you'll enable developer settings for AA. You'll see the option on the overflow icon in AA.

**Comment by iansalgado** [comment]
Oh you mean on the head unit

OK I will try that

Cheers

Ian Salgado
Email: ***@***.***
Mobile: 0415 515 086


-------- Original message --------
From: Jacob Celestine ***@***.***>
Date: Fri, 31 Mar 2023, 00:13
To: xManager-App/xManager ***@***.***>
Cc: iansalgado ***@***.***>, Mention ***@***.***>
Subject: Re: [xManager-App/xManager] xmanager-spotify Android Auto (Issue #296)

@iansalgado<https://github.com/iansalgado> Not your phone. You need to enable Android Auto developer settings. Go to settings, open android auto, click the version a few times and you'll enable developer settings for AA. You'll see the option on the overflow icon in AA.
