### ISSUE TITLE
Android Auto incompatibility

### ISSUE THREAD

**Issue by DarkXSeries7** [xManager-App/xManager#300]
this might be because of app version of whatever, but is there a way to spoof it in that case? no mention of spotify when you open the android auto app directory.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by DarkXSeries7** [comment]
having to go through a process and using third party devices means it's incompatible.

**Comment by DarkXSeries7** [comment]
having to go through a process and using third party devices means it's incompatible.

**Comment by JordySteyaert** [comment]
Go into the Developer settings in Android Auto and enable 'Unkown sources'. That fixes the issue.

Go to your Android settings -> use the search function to look for Android Auto -> scroll down to the version number -> tap it a few times until the developer settings are enabled -> press the menu in the top right and click on developer settings -> scroll down and enable 'Unkown sources'.

Happy Spotifying in your car :)
