### ISSUE TITLE
I don't know how to explain this bug?

### ISSUE THREAD

**Issue by Gamerboi520** [xManager-App/xManager#301]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy s21
- Android Version:  andriod 13
- ROM Version:  stock
- xManager Version: (4.8)
```

### 📝 Description

1. Uninstall current Spotify via Xmanager 
2. Attempt to install Spotify 8.8.22
3. Xmanager installs 8.8.14 instead of 8.8.22 even though i click 8.8.22
...

### 📸 Screenshots

![Screenshot_20230402_220049_xManager](https://user-images.githubusercontent.com/84089845/229395203-f67871a7-952a-4a68-a514-21e3c3b7b375.png)

**Comment by Gamerboi520** [comment]
Ugh then the bug fixes itself right after i submit an issue Lmao

**Comment by Gamerboi520** [comment]
(New Bug) when i try to download a playlist it crashes the app and recrashes everytime i even open the Spotify app (i have premium)

**Comment by xC3FFF0E** [comment]
> (New Bug) when i try to download a playlist it crashes the app and recrashes everytime i even open the Spotify app (i have premium)

It is a bug with the experimental patched and we are aware about this. Try using the stock patched instead.

Also, GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by Gamerboi520** [comment]
I've downloaded Stock patch and Amoled Patch even reinstalling the Xmanager app and Refetching the Datas it still crashes Spotify when downloading the playlists
