### ISSUE TITLE
Streaming to AV Receiver

### ISSUE THREAD

**Issue by NabsiYa** [xManager-App/xManager#303]
### Description of the new feature / enhancement

- Possibility of streaming straight to AV Receiver even if you are premium not user of Spotify.

### 📸 Screenshots

![IMG_20230407_183524](https://user-images.githubusercontent.com/43046474/230636255-e97871f6-14fd-4706-aede-15965d23be0f.jpg)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
