### ISSUE TITLE
patch capture stream 

### ISSUE THREAD

**Issue by mxwmnn** [xManager-App/xManager#307]
### Description of the new feature / enhancement

Would be nice like in ReVanced to patch the application that capturing the audio would be possible. I'm using rootlessjamesdsp and it can't process the audio.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
