### ISSUE TITLE
Tapping on mirror link crashes the app

### ISSUE THREAD

**Issue by AnonymouseHucker29** [xManager-App/xManager#311]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Realme Narzo 20
- Android Version:  11
- ROM Version:  Realme UI 2
- xManager Version:  4.8
```

### 📝 Description

1. Open xManager
2. Tap on _latest_ _release_ Spotify (8.8.28.409)
3. Tap on _mirror link_

App will crash and will output logs.

### 📸 Screenshots

![Screenshot_2023-05-04-15-39-28-19_a5c01c4563cf301fdcc1087d689ebdc7](https://user-images.githubusercontent.com/92257095/236144201-96780b4e-b5a4-4c1f-a002-667ccdcb705f.jpg)

**Comment by xC3FFF0E** [comment]
Mirror links should be up by now. Let me know if the persists.

**Comment by AnonymouseHucker29** [comment]
> Mirror links should be up by now. Let me know if the issue persists.

Mirror link now works. Thanks!
