### ISSUE TITLE
Can't sign in... 

### ISSUE THREAD

**Issue by MarshMeadow** [xManager-App/xManager#312]
I uninstalled it and installed it again and I tried to sign in but it could not access Spotify for some reason...

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
