### ISSUE TITLE
X Manager app does not force auto-install even though it is in the current version

### ISSUE THREAD

**Issue by Maremelows** [xManager-App/xManager#313]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:Samsung Galaxy A23
- Android Version:Android 13
- ROM Version:stock
- xManager Version:4.8
```

### 📝 Description

1.
2.
3.
...
Can I ask you something, why doesn't the Manager app auto-install when an update comes to modded spotify even though the force auto-install setting is on? I have to delete and reinstall spotify every time.

**Comment by xC3FFF0E** [comment]
The xManager's Auto-Install functionality is simply to bypass the 'apk installation' process. That doesn't mean it will automatically update the patched for you, no. You still need to download the latest version (if there's any available).
