### ISSUE TITLE
Ads while casting

### ISSUE THREAD

**Issue by pikachukaki** [xManager-App/xManager#323]
### Description of the new feature / enhancement

Im casting Spotify to my Xiaomi google speaker but it keeps sounding ads
Not sure if there is a solution. That's why I'm making this issue.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
